name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'
  AZURE_FUNCTIONAPP_NAME: grady-math-api
  AZURE_STATIC_WEB_APP_NAME: grady-math-web
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './MathWorksheetAPI'
  REACT_APP_PACKAGE_PATH: './grady-web'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    # API Build & Test
    - name: Install API Dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci

    - name: Build API
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm run build

    - name: Test API
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm test

    # Web App Build & Test
    - name: Install Web Dependencies
      run: |
        cd ${{ env.REACT_APP_PACKAGE_PATH }}
        npm ci

    - name: Build Web App
      run: |
        cd ${{ env.REACT_APP_PACKAGE_PATH }}
        npm run build

    - name: Test Web App
      run: |
        cd ${{ env.REACT_APP_PACKAGE_PATH }}
        npm test

    # Upload artifacts for deployment jobs
    - name: Upload API artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-build
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/build

    - name: Upload Web artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: ${{ env.REACT_APP_PACKAGE_PATH }}/build

  deploy-api:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: api-build
        path: api-build

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: api-build
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  deploy-web:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: web-build
        path: web-build

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "web-build"
        skip_app_build: true
